name: CI/CD Pipeline

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
        - name: Checkout repo
          uses: actions/checkout@v3
        
        - name: Set up Java
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: '17'

        - name: Increment version
          id: versioning
          run: |
           VERSION_FILE="VERSION"
            if [ ! -f "$VERSION_FILE" ]; then
              echo "1.0.0" > $VERSION_FILE
            fi
            
            OLD_VERSION=$(cat $VERSION_FILE)
            IFS='.' read -r MAJOR MINOR PATCH <<< "$OLD_VERSION"
            PATCH=$((PATCH + 1))
            NEW_VERSION="$MAJOR.$MINOR.$PATCH"
            echo "$NEW_VERSION" > $VERSION_FILE
            
            echo "New version: $NEW_VERSION"
            echo "VERSION=$NEW_VERSION" >> $GITHUB_ENV
          
        - name: Build JAR
          run: |
            mvn clean package
            mv target/my-app-1.0.0.jar target/my-app-${{ env.VERSION }}.jar
        
        - name: Build Docker image
          run: |
            docker build -t my-app:${{ env.VERSION }} . 
        
        - name: Create GitHub Release
          uses: softprops/action-gh-release@v1
          with:
            tag_name: v${{ env.VERSION }}
            files: target/my-app-${{ env.VERSION }}.jar
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          